import 'package:flex_color_scheme/flex_color_scheme.dart';
import 'package:flutter/material.dart';

class ThemeChangeNotifier extends ChangeNotifier {
  final List<ThemeData> themeList = [
    FlexThemeData.light(
      scheme: FlexScheme.materialHc,
      surfaceMode: FlexSurfaceMode.levelSurfacesLowScaffold,
      blendLevel: 7,
      appBarStyle: FlexAppBarStyle.primary,
      subThemesData: const FlexSubThemesData(
        blendOnLevel: 10,
        blendOnColors: false,
        blendTextTheme: true,
        useTextTheme: true,
        thinBorderWidth: 1.0,
        thickBorderWidth: 2.5,
        checkboxSchemeColor: SchemeColor.primary,
        chipSchemeColor: SchemeColor.primary,
        chipSelectedSchemeColor: SchemeColor.onSecondary,
        chipDeleteIconSchemeColor: SchemeColor.secondary,
        cardRadius: 6.0,
        popupMenuSchemeColor: SchemeColor.primary,
        alignedDropdown: true,
        dialogBackgroundSchemeColor: SchemeColor.surface,
        dialogElevation: 6.0,
        useInputDecoratorThemeInDialogs: true,
      ),
      visualDensity: FlexColorScheme.comfortablePlatformDensity,
      useMaterial3: false,
      // To use the Playground font, add GoogleFonts package and uncomment
      // fontFamily: GoogleFonts.notoSans().fontFamily,
    ),
    FlexThemeData.light(
      scheme: FlexScheme.red,
      surfaceMode: FlexSurfaceMode.levelSurfacesLowScaffold,
      blendLevel: 7,
      appBarStyle: FlexAppBarStyle.primary,
      subThemesData: const FlexSubThemesData(
        blendOnLevel: 10,
        blendOnColors: false,
        blendTextTheme: true,
        useTextTheme: true,
        thinBorderWidth: 1.0,
        thickBorderWidth: 2.5,
        checkboxSchemeColor: SchemeColor.primary,
        chipSchemeColor: SchemeColor.primary,
        chipSelectedSchemeColor: SchemeColor.onSecondary,
        chipDeleteIconSchemeColor: SchemeColor.secondary,
        cardRadius: 6.0,
        popupMenuSchemeColor: SchemeColor.primary,
        alignedDropdown: true,
        dialogBackgroundSchemeColor: SchemeColor.surface,
        dialogElevation: 6.0,
        useInputDecoratorThemeInDialogs: true,
      ),
      visualDensity: FlexColorScheme.comfortablePlatformDensity,
      useMaterial3: false,
      // To use the Playground font, add GoogleFonts package and uncomment
      // fontFamily: GoogleFonts.notoSans().fontFamily,
    ),
    FlexThemeData.light(
      scheme: FlexScheme.blue,
      surfaceMode: FlexSurfaceMode.levelSurfacesLowScaffold,
      blendLevel: 7,
      appBarStyle: FlexAppBarStyle.primary,
      subThemesData: const FlexSubThemesData(
        blendOnLevel: 10,
        blendOnColors: false,
        blendTextTheme: true,
        useTextTheme: true,
        thinBorderWidth: 1.0,
        thickBorderWidth: 2.5,
        checkboxSchemeColor: SchemeColor.primary,
        chipSchemeColor: SchemeColor.primary,
        chipSelectedSchemeColor: SchemeColor.onSecondary,
        chipDeleteIconSchemeColor: SchemeColor.secondary,
        cardRadius: 6.0,
        popupMenuSchemeColor: SchemeColor.primary,
        alignedDropdown: true,
        dialogBackgroundSchemeColor: SchemeColor.surface,
        dialogElevation: 6.0,
        useInputDecoratorThemeInDialogs: true,
      ),
      visualDensity: FlexColorScheme.comfortablePlatformDensity,
      useMaterial3: false,
      // To use the Playground font, add GoogleFonts package and uncomment
      // fontFamily: GoogleFonts.notoSans().fontFamily,
    ),
    FlexThemeData.light(
      scheme: FlexScheme.sakura,
      surfaceMode: FlexSurfaceMode.levelSurfacesLowScaffold,
      blendLevel: 7,
      appBarStyle: FlexAppBarStyle.primary,
      subThemesData: const FlexSubThemesData(
        blendOnLevel: 10,
        blendOnColors: false,
        blendTextTheme: true,
        useTextTheme: true,
        thinBorderWidth: 1.0,
        thickBorderWidth: 2.5,
        checkboxSchemeColor: SchemeColor.primary,
        chipSchemeColor: SchemeColor.primary,
        chipSelectedSchemeColor: SchemeColor.onSecondary,
        chipDeleteIconSchemeColor: SchemeColor.secondary,
        cardRadius: 6.0,
        popupMenuSchemeColor: SchemeColor.primary,
        alignedDropdown: true,
        dialogBackgroundSchemeColor: SchemeColor.surface,
        dialogElevation: 6.0,
        useInputDecoratorThemeInDialogs: true,
      ),
      visualDensity: FlexColorScheme.comfortablePlatformDensity,
      useMaterial3: false,
      // To use the Playground font, add GoogleFonts package and uncomment
      // fontFamily: GoogleFonts.notoSans().fontFamily,
    ),
    FlexThemeData.light(
      scheme: FlexScheme.green,
      surfaceMode: FlexSurfaceMode.levelSurfacesLowScaffold,
      blendLevel: 7,
      appBarStyle: FlexAppBarStyle.primary,
      subThemesData: const FlexSubThemesData(
        blendOnLevel: 10,
        blendOnColors: false,
        blendTextTheme: true,
        useTextTheme: true,
        thinBorderWidth: 1.0,
        thickBorderWidth: 2.5,
        checkboxSchemeColor: SchemeColor.primary,
        chipSchemeColor: SchemeColor.primary,
        chipSelectedSchemeColor: SchemeColor.onSecondary,
        chipDeleteIconSchemeColor: SchemeColor.secondary,
        cardRadius: 6.0,
        popupMenuSchemeColor: SchemeColor.primary,
        alignedDropdown: true,
        dialogBackgroundSchemeColor: SchemeColor.surface,
        dialogElevation: 6.0,
        useInputDecoratorThemeInDialogs: true,
      ),
      visualDensity: FlexColorScheme.comfortablePlatformDensity,
      useMaterial3: false,
      // To use the Playground font, add GoogleFonts package and uncomment
      // fontFamily: GoogleFonts.notoSans().fontFamily,
    ),
    FlexThemeData.light(
      scheme: FlexScheme.greyLaw,
      surfaceMode: FlexSurfaceMode.levelSurfacesLowScaffold,
      blendLevel: 7,
      appBarStyle: FlexAppBarStyle.primary,
      subThemesData: const FlexSubThemesData(
        blendOnLevel: 10,
        blendOnColors: false,
        blendTextTheme: true,
        useTextTheme: true,
        thinBorderWidth: 1.0,
        thickBorderWidth: 2.5,
        checkboxSchemeColor: SchemeColor.primary,
        chipSchemeColor: SchemeColor.primary,
        chipSelectedSchemeColor: SchemeColor.onSecondary,
        chipDeleteIconSchemeColor: SchemeColor.secondary,
        cardRadius: 6.0,
        popupMenuSchemeColor: SchemeColor.primary,
        alignedDropdown: true,
        dialogBackgroundSchemeColor: SchemeColor.surface,
        dialogElevation: 6.0,
        useInputDecoratorThemeInDialogs: true,
      ),
      visualDensity: FlexColorScheme.comfortablePlatformDensity,
      useMaterial3: false,
      // To use the Playground font, add GoogleFonts package and uncomment
      // fontFamily: GoogleFonts.notoSans().fontFamily,
    ),
    FlexThemeData.light(
      scheme: FlexScheme.amber,
      surfaceMode: FlexSurfaceMode.levelSurfacesLowScaffold,
      blendLevel: 7,
      appBarStyle: FlexAppBarStyle.primary,
      subThemesData: const FlexSubThemesData(
        blendOnLevel: 10,
        blendOnColors: false,
        blendTextTheme: true,
        useTextTheme: true,
        thinBorderWidth: 1.0,
        thickBorderWidth: 2.5,
        checkboxSchemeColor: SchemeColor.primary,
        chipSchemeColor: SchemeColor.primary,
        chipSelectedSchemeColor: SchemeColor.onSecondary,
        chipDeleteIconSchemeColor: SchemeColor.secondary,
        cardRadius: 6.0,
        popupMenuSchemeColor: SchemeColor.primary,
        alignedDropdown: true,
        dialogBackgroundSchemeColor: SchemeColor.surface,
        dialogElevation: 6.0,
        useInputDecoratorThemeInDialogs: true,
      ),
      visualDensity: FlexColorScheme.comfortablePlatformDensity,
      useMaterial3: false,
      // To use the Playground font, add GoogleFonts package and uncomment
      // fontFamily: GoogleFonts.notoSans().fontFamily,
    ),
    FlexThemeData.light(
      scheme: FlexScheme.bahamaBlue,
      surfaceMode: FlexSurfaceMode.levelSurfacesLowScaffold,
      blendLevel: 7,
      appBarStyle: FlexAppBarStyle.primary,
      subThemesData: const FlexSubThemesData(
        blendOnLevel: 10,
        blendOnColors: false,
        blendTextTheme: true,
        useTextTheme: true,
        thinBorderWidth: 1.0,
        thickBorderWidth: 2.5,
        checkboxSchemeColor: SchemeColor.primary,
        chipSchemeColor: SchemeColor.primary,
        chipSelectedSchemeColor: SchemeColor.onSecondary,
        chipDeleteIconSchemeColor: SchemeColor.secondary,
        cardRadius: 6.0,
        popupMenuSchemeColor: SchemeColor.primary,
        alignedDropdown: true,
        dialogBackgroundSchemeColor: SchemeColor.surface,
        dialogElevation: 6.0,
        useInputDecoratorThemeInDialogs: true,
      ),
      visualDensity: FlexColorScheme.comfortablePlatformDensity,
      useMaterial3: false,
      // To use the Playground font, add GoogleFonts package and uncomment
      // fontFamily: GoogleFonts.notoSans().fontFamily,
    ),
    FlexThemeData.light(
      scheme: FlexScheme.outerSpace,
      surfaceMode: FlexSurfaceMode.levelSurfacesLowScaffold,
      blendLevel: 7,
      appBarStyle: FlexAppBarStyle.primary,
      subThemesData: const FlexSubThemesData(
        blendOnLevel: 10,
        blendOnColors: false,
        blendTextTheme: true,
        useTextTheme: true,
        thinBorderWidth: 1.0,
        thickBorderWidth: 2.5,
        checkboxSchemeColor: SchemeColor.primary,
        chipSchemeColor: SchemeColor.primary,
        chipSelectedSchemeColor: SchemeColor.onSecondary,
        chipDeleteIconSchemeColor: SchemeColor.secondary,
        cardRadius: 6.0,
        popupMenuSchemeColor: SchemeColor.primary,
        alignedDropdown: true,
        dialogBackgroundSchemeColor: SchemeColor.surface,
        dialogElevation: 6.0,
        useInputDecoratorThemeInDialogs: true,
      ),
      visualDensity: FlexColorScheme.comfortablePlatformDensity,
      useMaterial3: false,
      // To use the Playground font, add GoogleFonts package and uncomment
      // fontFamily: GoogleFonts.notoSans().fontFamily,
    ),
    FlexThemeData.light(
      scheme: FlexScheme.pinkM3,
      surfaceMode: FlexSurfaceMode.levelSurfacesLowScaffold,
      blendLevel: 7,
      appBarStyle: FlexAppBarStyle.primary,
      subThemesData: const FlexSubThemesData(
        blendOnLevel: 10,
        blendOnColors: false,
        blendTextTheme: true,
        useTextTheme: true,
        thinBorderWidth: 1.0,
        thickBorderWidth: 2.5,
        checkboxSchemeColor: SchemeColor.primary,
        chipSchemeColor: SchemeColor.primary,
        chipSelectedSchemeColor: SchemeColor.onSecondary,
        chipDeleteIconSchemeColor: SchemeColor.secondary,
        cardRadius: 6.0,
        popupMenuSchemeColor: SchemeColor.primary,
        alignedDropdown: true,
        dialogBackgroundSchemeColor: SchemeColor.surface,
        dialogElevation: 6.0,
        useInputDecoratorThemeInDialogs: true,
      ),
      visualDensity: FlexColorScheme.comfortablePlatformDensity,
      useMaterial3: false,
      // To use the Playground font, add GoogleFonts package and uncomment
      // fontFamily: GoogleFonts.notoSans().fontFamily,
    ),
    FlexThemeData.light(
      scheme: FlexScheme.purpleM3,
      surfaceMode: FlexSurfaceMode.levelSurfacesLowScaffold,
      blendLevel: 7,
      appBarStyle: FlexAppBarStyle.primary,
      subThemesData: const FlexSubThemesData(
        blendOnLevel: 10,
        blendOnColors: false,
        blendTextTheme: true,
        useTextTheme: false,
        thinBorderWidth: 1.0,
        thickBorderWidth: 2.5,
        checkboxSchemeColor: SchemeColor.primary,
        chipSchemeColor: SchemeColor.primary,
        chipSelectedSchemeColor: SchemeColor.onSecondary,
        chipDeleteIconSchemeColor: SchemeColor.secondary,
        cardRadius: 6.0,
        popupMenuSchemeColor: SchemeColor.primary,
        alignedDropdown: true,
        dialogBackgroundSchemeColor: SchemeColor.surface,
        dialogElevation: 6.0,
        dialogRadius: 32.0,
        useInputDecoratorThemeInDialogs: true,
      ),
      visualDensity: FlexColorScheme.comfortablePlatformDensity,
      useMaterial3: false,
      // To use the Playground font, add GoogleFonts package and uncomment
      // fontFamily: GoogleFonts.notoSans().fontFamily,
    ),
    FlexThemeData.light(
      colors: const FlexSchemeColor(
        primary: Color(0xff004881),
        primaryContainer: Color(0xffd0e4ff),
        secondary: Color(0xffac3306),
        secondaryContainer: Color(0xffffdbcf),
        tertiary: Color(0xff006875),
        tertiaryContainer: Color(0xff95f0ff),
        appBarColor: Color(0xffffdbcf),
        error: Color(0xffb00020),
      ),
      surfaceMode: FlexSurfaceMode.levelSurfacesLowScaffold,
      blendLevel: 7,
      appBarStyle: FlexAppBarStyle.primary,
      subThemesData: const FlexSubThemesData(
        blendOnLevel: 10,
        blendOnColors: false,
        blendTextTheme: true,
        useTextTheme: false,
        thinBorderWidth: 1.0,
        thickBorderWidth: 2.5,
        checkboxSchemeColor: SchemeColor.primary,
        chipSchemeColor: SchemeColor.primary,
        chipSelectedSchemeColor: SchemeColor.onSecondary,
        chipDeleteIconSchemeColor: SchemeColor.secondary,
        cardRadius: 6.0,
        popupMenuSchemeColor: SchemeColor.primary,
        alignedDropdown: true,
        dialogBackgroundSchemeColor: SchemeColor.surface,
        dialogElevation: 6.0,
        dialogRadius: 32.0,
        useInputDecoratorThemeInDialogs: true,
      ),
      visualDensity: FlexColorScheme.comfortablePlatformDensity,
      useMaterial3: false,
      // To use the Playground font, add GoogleFonts package and uncomment
      // fontFamily: GoogleFonts.notoSans().fontFamily,
    ),
  ];

  ThemeData _themeData = ThemeData(
      colorScheme: const ColorScheme.light(
        primary: Colors.red,
      ),
      cardTheme: const CardTheme(shadowColor: Colors.red));

  ///ThemeData 可以设置各种各样的样式和主题，比如按钮样式，弹窗样式，以及其他组件的样式
  ///可以通过Theme.of(context).    来获取全局的样式
  ThemeData get themeData => _themeData;

  void setThemeData(int index) {
    _themeData = themeList[index];
    notifyListeners();
  }
}
